export const CATEGORY_CONCESIONARIAS = 'CATEGORY_CONCESIONARIAS';
export const CATEGORY_VIVIENDAS = 'CATEGORY_VIVIENDAS';
export const CATEGORY_BARES = 'CATEGORY_BARES';

export const SET_GALLERY_BY_ID = 'SET_GALLERY_BY_ID';
